FROM ubuntu:18.04

RUN apt-get update && apt-get install -y zip

# support lets encrypt root CA
RUN curl https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem > /usr/local/share/ca-certificates/letencrypt.crt

RUN update-ca-certificates 

# ref circle ci config artifacts path
COPY ./artifacts/build/cachetmonitor-linux-amd64.zip .

RUN unzip ./cachetmonitor-linux-amd64.zip

ENV AUTO_CONFIG true

CMD ["./cachetmonitor-linux-amd64"]